workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      # - name: Run tests
      #   script: flutter test
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
      - name: Upload Artifacts to GitHub
        script: |
          curl -X POST https://api.github.com/repos/Azthriel/REPO/Ing_app_57 \
          -H "Authorization: token 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" \
          -d '{"tag_name": "v1.0.0", "target_commitish": "master", "name": "v1.0.0", "body": "Description of the release", "draft": false, "prerelease": false}'
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - trillogonzalolaboral@gmail.com
