name: ing_config_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15
  flutter_blue_plus: ^1.29.12
  qr_code_scanner: ^1.0.1
  share: ^2.0.4
  easy_refresh: ^3.3.2+4
  dio: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  icons_launcher: ^2.1.7


icons_launcher:
  image_path: 'assets/iconosky.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/iconosky.png'
      adaptive_background_image: 'assets/background.png'
      adaptive_foreground_image: 'assets/iconosky.png'
    ios:
      enable: true


flutter:

  uses-material-design: true

  assets:
    - assets/ingAppLogo.png
    - assets/iconosky.png
    - assets/background.png